apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
data:
  db_passwd: Y29uZHVpdAo=
  db_user: Y29uZHVpdAo=
  db_name: Y29uZHVpdAo=

---
#Root password secret
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysql-root-pass
# type: Opaque
# data:
#   password: cm9vdHBhc3N3b3Jk